version: '3'

services:

  redis-server:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - 6379:6379 
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  

  nestjs-app:
    build:
      context: .
      dockerfile: ./apps/dice-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
     redis-server:
       condition: service_healthy
    restart: unless-stopped
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
  
  nginx-react-app:
    build:
      context: .
      dockerfile: ./apps/dice-app/Dockerfile
    ports:
      - "8080:80"
 

